### PR TITLE
New rules for 2018

### PR DESCRIPTION
**Pull request by TheEadie**
- Move all super weapons to turn 6
+ add Holy hand grenade

### CODE REVIEW

**Comment by PeterGerrard** [comment]
Baseball bat as well?

**Comment by Michael-Upton** [comment]
+jet-pack?

**Comment by TheEadie** [comment]
- I think baseball bat is very powerful - it'll become the default turn 1 weapon again otherwise.
- Jet pack opens up Banana + Jet Pack move again - do we want that?

**Comment by PeterGerrard** [comment]
- I'm not suggesting baseball turn 1, just not on super turn.
- Rather not add jet pack back for that exact reason

**Comment by Michael-Upton** [comment]
More ninjas then.

**Comment by mark-raymond** [comment]
Presumably the intent of this is to avoid the situation of "it's go x, therefore everyone uses y", because everything is enabled on the same go, so you actually have to make a choice?

I quite like that idea, although moving *everything* to go 6 might mean the early game is a little boring. Perhaps a subset (the less powerful ones) could be enabled all at once on go 3?

Also, 👍 to adding Low Gravity :)

**Comment by TheEadie** [comment]
Yeah the intent is for more choice since you can't just use a certain item on each turn.

If we were to have a set of weapons that would be on turn 3 what do we think they should be?

**Comment by mark-raymond** [comment]
Candidates would be Dynamite, Sheep, Sheep Launcher and Mole Bomb, I think. Dynamite used to be turn 3. Sheep Launcher and Mole Bomb are kinda useless but funny, so I think they'd be safe to add on turn 3. Sheep was available on turn 1 before, and we don't use it that much.

**Comment by PeterGerrard** [comment]
Possibly also baseball bat to 3

**Comment by mark-raymond** [comment]
I don't think baseball bat should be before go 5, so that every worm has a chance to move off the edge.

**Comment by Michael-Upton** [comment]
If you're saying every worm needs a chance to move off the edge, then bow+arrow needs delaying too.

How about 2 switch worms instead of 1?

**Comment by mark-raymond** [comment]
Ooh, more switch worms could definitely be interesting!

**Pull request merged**
