### PR TITLE
Add random scheme generation

### PR DESCRIPTION
**Pull request by PeterGerrard**
This is an port of (a simplified version of) #33.

~~NB. It changes the short code for resourceFolder to -o over -r as -r is better for random and -o as shorthand for output~~
-> No longer true, removed this as its a larger (breaking) change that turned out to be un-necessary

### CODE REVIEW

**Comment by TheEadie** [comment]
I'll have a look in detail next week, but this is something I wanted to add.

On the short option change. I was trying to reserve `-o` for changing the output format, that way you could choose between `human|json|yaml`. I'd already thought `r` would have to change though as it often means `replay` in this domain. Any other ideas of what we could use for the folder override? `-f` is too common with force?

**Comment by TheEadie** [comment]
Maybe `-i` for input file, `-o` for output folder and `-f` for format?

**Comment by PeterGerrard** [comment]
Good points, consistency is better, for now let me see if I can turn off short name for random.

**Comment by PeterGerrard** [comment]
For what short-codes to use I've found that there isn't really much consistency across CLIs, its more important to be consistent within.

I've seen:
Input: `-i` and `-f`, rarely `-s` (source)
Output: `-o` and `-f` (f is used more when its and output folder), rarely `-t` (target)
Format: `-o` and `-f`

**Comment by TheEadie** [comment]
I'll probably do some refactoring:
- I think the random scheme code probably belongs in the `Worms.Cli.Resources` module rather than the files module. I want to try and keep the files module to only be about interacting with the Worms Armaggedon files on disk. It could go either way though.
- Rather than have an additional `LocalSchemeRandomCreator` I'd probably add `random` to the `LocalSchemeCreateParameters` and then do the switching at that level rather than in the CLI command. This will be annoying as we get into having parameter sets and `null` pointers but it feels cleaner than having lots of interfaces.

Happy to merge as is though and I'll circle back to those changes when I find some time in a few months :)

**Pull request merged**
