### PR TITLE
Reduce girders to 1 Ammo

### PR DESCRIPTION
**Pull request by TheEadie**
image

### CODE REVIEW

**Comment by Michael-Upton** [comment]
http://giphy.com/gifs/VLoN2iW8ii3wA/html5

**Comment by tomcsmith1990** [comment]
Nah

**Comment by GrahamTheCoder** [comment]
I haven't been in a game where it's caused any problem. Placing a girder takes one turn, shotgunning through takes half a turn.

**Comment by Michael-Upton** [comment]
Yes, but half a turn to shotgun through, half a turn to not kill, means a whole turn wasted trying to get through.

**Comment by tomcsmith1990** [comment]
Girders are also useful for climbing when ninja ropes/jet packs run out.

**Comment by GrahamTheCoder** [comment]
We could massively delay all girders for that purpose I guess

**Comment by TheEadie** [comment]
The council have spoken - Fewer girders it is. (6 for, 3 against)

**Pull request merged**
