### PR TITLE
Make mole bombs crazy powerful

### PR DESCRIPTION
**Pull request by TheEadie**
Makes mole bombs much more powerful so they are actually useful. (See table from http://worms2d.info/Mole_Bomb)

Power	Maximum injury	Crater diameter
11	15 hp	35 px
12	21	47
1	24	47
2	27	61
3	30	61
4	33	61
5	36	73
19	39	73
14	45	85
15	60	123

### CODE REVIEW

**Comment by mark-raymond** [comment]
What diameter is the crater for eg. dynamite, sheep, grenade, mine?

**Comment by TheEadie** [comment]
I think the mole should be as powerful as a sheep. Its fairly hard to predict where its going to go (mostly because we never use them) and is effective against darksiders.

**Comment by GrahamTheCoder** [comment]
Yeah as long a it's just in crates, being slightly better than dynamite seems right

**Comment by samblackburn** [comment]
I'm fine with overdoing it - if they become too powerful then we can always tone them down later

**Pull request merged**
