### PR TITLE
Remove banana bomb from default weapons

### PR DESCRIPTION
**Pull request by TheEadie**
Make them crate only

### CODE REVIEW

**Comment by mark-raymond** [comment]
I would be sad to see the banana bomb go. Is the issue that people are too good at using them now, so they don't provide the randomization/entertainment value they used to?

**Comment by TheEadie** [comment]
This was proposed by @Michael-Upton.

Conversation from Slack:

Controversial proposal (I think seconded by Peter) - stop banana bomb being in your default weapon set, make it crate only.

David Eadie [1:05 PM] 
We previously discussed this here: https://github.com/TheEadie/WormsLeague/pull/12
GitHub
Banana bombs are OP - make them crate only by Michael-Upton · Pull Request #12 · TheEadie/WormsLeague · GitHub
Changed the default ammo for banana bomb to zero, made them as likely to appear in crates as any other normal weapon, and reduced the delay so they might start appearing in crates earlier.
 

Sam '); DROP TABLE Blackburn [1:06 PM] 
Are they already minimum damage?  Or would that be less fun?

David Eadie [1:08 PM] 
tempted to write the rule set randomiser

Mike Upton [1:08 PM] 
I think we end up waiting for the banana bomb, and much of the game hinges around who went first and therefore gets the banana bomb first.

[1:09]  
And it's more destructive than any of the team special weapons, and probably most of the super weapons as well.

David Eadie [1:11 PM] 
I'm not against getting rid of them tbh

[1:12]  
but I think crates might have to be a bit more interesting

[1:12]  
The game might be a bit dull with only shotguns and mines

Peter Gerrard [1:12 PM] 
If we got rid of Banana bombs I'd possibly bring back JetPacks

Mike Upton [1:13 PM] 
And we do seem to get a relatively high proportion of super weapons in crates. But I agree, we could do with tweaking them for maximum fun.

**Comment by TheEadie** [comment]
I'd like to see something crazy take its place if we do remove it. Maybe a `Damage x2` each or something else?

**Comment by mark-raymond** [comment]
> Maybe a `Damage x2` each or something else?

I'm not sure what you mean here - double damage can only be picked up from a toolbox and only applied that turn I thought? How could you have one each?

**Comment by TheEadie** [comment]
We can give everyone anything from the toolbox crates as part of the standard weapon set. We used to do this for jetpacks before we removed them. We could have some interesting game play from people choosing when they wanted to use their double damage, though I suspect moves like double damage ->mad cows might become very common.

**Comment by mark-raymond** [comment]
And given the size of the resultant explosions, you'd probably kill yourself too 😃 

I think it would be worth testing what happens if you enable that. I don't know what that would look like in the UI.

**Comment by PeterGerrard** [comment]
For reference I tried this at one point with double damage. The first one you add is auto used turn 1. Subsequent additions go into the inventory for future use.

**Comment by TheEadie** [comment]
Going to close this as it seems too controversial to be made

**Pull request closed without merging**
